spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/transportador
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
